# Generated by Django 5.2.1 on 2025-06-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_other_type_name_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('hackathon', 'Hackathon'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('competition', 'Competition'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('others', 'Others')], default='hackathon', max_length=50),
        ),
    ]
